/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class vehicles_ef : vehicles_base
{
    ITEM(EF_O_Gyra_Antiair_OPF, 14250, "AA", VEHICLE_CONDITION_AA);
    ITEM(EF_O_Gyra_Armed_OPF, 20820, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_O_Gyra_HMG_OPF, 8320, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_O_Gyra_OPF, 3900, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_O_Gyra_Mortar_OPF, 26400, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(EF_QAV80_MJTF_Des, 42650, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(EF_QAV80_Stealth_MJTF_Des, 29800, "UAV", VEHICLE_CONDITION_UAV);
};